# Generated by Django 5.1.1 on 2024-10-01 05:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0003_weightentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeightEntry',
            new_name='WeightRecord',
        ),
        migrations.AlterUniqueTogether(
            name='weightrecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='weightuser',
            name='weight',
        ),
    ]
