# Generated by Django 5.1.1 on 2024-10-05 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0004_rename_weightentry_weightrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightrecord',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weight.weightuser'),
        ),
    ]
